### ISSUE TITLE
Boton de Perfil de usuario no tiene ninguna funcion

### ISSUE THREAD

**Issue by JosePolancoR** [jairist/happy-web#10]
SO: Windows 10
Navegador: Google Chrome
Ambiente: Prueba

Pasos para replicar:
1- Acceder al link web de Happy
2- Iniciar sesión con un usuario ya registrado y clickear ingresar
3- Clickerar boton de perfil de usuario

Resultado esperado:
* Debe diseccionarse a una pantalla con la informacion del usuario

Resultado obtenido: 
* El botón no muestra ninguna función
![image](https://user-images.githubusercontent.com/54126644/99341946-37522080-2861-11eb-9641-cf301cbbd4a3.png)

**Comment by jairist** [comment]
Ese ícono no se estará utilizando en el proyecto así que fué removido. 
![image](https://user-images.githubusercontent.com/2242257/104390065-38c36080-5513-11eb-8fb3-6157fb5deeb1.png)
