### ISSUE TITLE
Pantalla de lista de Proveedores no carga

### ISSUE THREAD

**Issue by JosePolancoR** [jairist/happy-web#11]
SO: Windows 10
Navegador: Google Chrome
Ambiente: Prueba

Pasos para replicar:
1- Acceder al link web de Happy
2- Iniciar sesión con un usuario ya registrado y clickear ingresar
3- Clickear en el menu el botón de Lista de proveedores

Resultado esperado:
* La pantalla de lista de proveedores debe cargar con la información pertinente

Resultado obtenido: 
* La pantalla no muestra ninguna información
![image](https://user-images.githubusercontent.com/54126644/99342321-045c5c80-2862-11eb-92fd-5a24578b06b6.png)

**Comment by jairist** [comment]
Lista de proveedores ya esta cargando correctamente, se debía a una falla en la conexión con firebase. 
![image](https://user-images.githubusercontent.com/2242257/104390140-64dee180-5513-11eb-8b74-8945f7bbccbc.png)

**Comment by jairist** [comment]
LIsto
