### ISSUE TITLE
La aplicación valida campos vacios

### ISSUE THREAD

**Issue by JosePolancoR** [jairist/happy-web#14]
SO: Windows 10
Navegador: Google Chrome
Ambiente: Prueba

Pasos para replicar:
1- Acceder al link web de Happy
2- Iniciar sesión con un usuario ya registrado y clickear ingresar
3- Ir al "Agregar proveedor"
4- Introducir la informacion del proveedors y clickear "Agregar nuevo proveedor"
5- Cerrar sesión
6- Iniciar sesión nuevamente
7- Ir a "Agregar proveedor"
8- Clickear nuevamente "Agregar nuevo proveedor"

Resultado esperado:
* La pantalla debe cargar con todos los campos vacios y sin rastros de los datos anteriores

Resultado obtenido:
* La pantalla carga con los campos vacios, pero muestra los datos anteriores como validaciones y permite agregarlos nuevamente.
![chrome-capture (2)](https://user-images.githubusercontent.com/54126644/99345437-b1d26e80-2868-11eb-8313-a227c29677de.gif)

**Comment by jairist** [comment]
Fue agregada la validación para no permitir agregar sin el nombre y la descripción. 
![image](https://user-images.githubusercontent.com/2242257/104385765-34467a00-550a-11eb-8a6a-e51c4ba70ca7.png)

**Comment by jairist** [comment]
Adicional se colocó validación para que que botón no se habilite si los campos no están llenos. 
![image](https://user-images.githubusercontent.com/2242257/104388606-d6b52c00-550f-11eb-8194-04cda6c171ae.png)
![image](https://user-images.githubusercontent.com/2242257/104388635-e6cd0b80-550f-11eb-8636-71b797dd92d6.png)
y si se intenta agregar sin los datos se presenta un mensaje indicado que los campos son requerido. 
![image](https://user-images.githubusercontent.com/2242257/104388677-08c68e00-5510-11eb-9db8-1afdbea1079b.png)

**Comment by jairist** [comment]
Defecto corregido se procede a cerrar el issue
